### ISSUE TITLE
ERROR Cannot assign to read only property 'index' of object '#<Object>' TypeError: Cannot assign to read only property 'index' of object

### ISSUE THREAD

**Issue by harikaran03** [karolkozer/planby#65]
ERROR
Cannot assign to read only property 'index' of object '#<Object>'
TypeError: Cannot assign to read only property 'index' of object '#<Object>'
    at setLayoutScreenCloneElement (webpack://datastore_vod_ui/../node_modules/@nessprim/planby-pro/dist/planby-pro.esm.js?:737:25)
    at renderPrograms (webpack://datastore_vod_ui/../node_modules/@nessprim/planby-pro/dist/planby-pro.esm.js?:4668:7)
    at eval (webpack://datastore_vod_ui/../node_modules/@nessprim/planby-pro/dist/planby-pro.esm.js?:4818:12)
    at Array.map (<anonymous>)
    at eval (webpack://datastore_vod_ui/../node_modules/@nessprim/planby-pro/dist/planby-pro.esm.js?:4817:15)
    at renderWithHooks (http://localhost:3000/main.js:17259:18)
    at updateForwardRef (http://localhost:3000/main.js:20175:20)
    at beginWork (http://localhost:3000/main.js:22585:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/main.js:5118:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/main.js:5167:16)

**Comment by karolkozer** [comment]
Hi @harikaran03,

Can you provide more information when this error is occuring?
Can you send me some code or codesandbox link to check the issue?

**Comment by shivamchamoli09** [comment]
Facing the same issue. I am not yet able to exactly find when and where this is happening as this occurs intermittently. This is happening when I am scrolling fast over the timeline region. In my case, the layout is being changed as certain sidebars are being opened and closed regularly. Once this window is changed and then when I scroll over the timeline, after certain period, this error is thrown, but not sure if this is the only reason.

**Comment by shivamchamoli09** [comment]
Hi, is there any update on this issue?
